# -*- mode: ruby -*-
# vi: set ft=ruby :

Dotenv.load

Vagrant.configure("2") do |config|

  boxes = [
    { :name => "runner", :cpus => 2, :memory => 6144, :disk => '30GB'  },
  ]

  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"
  config.vm.provider "vmware_fusion" do |vmware|
    vmware.allowlist_verified = true
  end

  # disable the default synced_folder and sync the root folder
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../", "/vagrant", privileged: true

  # config.vm.box_check_update = true

  boxes.each do |opts|
    config.vm.define opts[:name] do |box|

      box.vm.provider "vmware_fusion" do |vb|
        # Display the VirtualBox GUI when booting the machine
        vb.gui = false

        # Customize the amount of cpus and memory on the VM:
        vb.cpus = opts[:cpus]
        vb.memory = opts[:memory]
        # vb.disk :disk, size: "opts[:disk]", primary: true

        # Fix https://www.virtualbox.org/ticket/15705
        # vb.customize ["modifyvm", :id, "--cableconnected1", "on"]

      end

      box.vm.provision "shell", inline: "cat /vagrant/keys/vagrant_id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", privileged: false
      box.vm.provision "shell", inline: "echo 'cd /vagrant' >> ~/.bashrc", privileged: false

    end
  end



  config.vm.provision :root_user, type: "shell", path: "provision_root.sh"
  config.vm.provision :vagrant_user, type: "shell", privileged: false, path: "provision_nonroot.sh"

  config.vm.provision "GHR-Install",  type:"shell", run: "never", privileged: false, inline: <<-SHELL
    # Install actions/runner
    GHA_RUNNER_VERSION="2.287.1"
    GHA_NAME_OS_ARCH="linux-arm64"
    mkdir ~/actions-runner && cd ~/actions-runner
    curl -so actions-runner-${GHA_NAME_OS_ARCH}-${GHA_RUNNER_VERSION}.tar.gz -L https://github.com/actions/runner/releases/download/v${GHA_RUNNER_VERSION}/actions-runner-${GHA_NAME_OS_ARCH}-${GHA_RUNNER_VERSION}.tar.gz
    echo "9a59cb84458b27767e082080e7b575e42b36f0e32a493fc9627ca8e29f4b3346  actions-runner-${GHA_NAME_OS_ARCH}-${GHA_RUNNER_VERSION}.tar.gz" | shasum -a 256 -c
    tar xzf ./actions-runner-${GHA_NAME_OS_ARCH}-${GHA_RUNNER_VERSION}.tar.gz
    ./config.sh --unattended --url #{ENV['GHA_RUNNER_URL']} --token #{ENV['GHA_RUNNER_TOKEN']} --replace --name #{ENV['GHA_RUNNER_NAME']} --labels #{ENV['GHA_RUNNER_NAME']} --work _work
    nohup ./run.sh &
  SHELL

end
